import type { TimelineEvent } from "./TimelineDock";

// Source-backed events published in the public dock at the owner's request.
// These short entries do not need separate long-form article pages.
export const timelineEvents: TimelineEvent[] = [
  {
    id: "handaxes",
    date: "1.76 million years ago",
    shortDate: "1.76m years ago",
    era: "Early humans",
    title: "A sharper idea",
    text: "Early humans were shaping stone into Acheulean handaxes and other large cutting tools by about 1.76 million years ago. Those stones still carry clues to the skills and thinking that went into making them.",
    source: "Smithsonian Human Origins",
    url: "https://humanorigins.si.edu/evidence/behavior/stone-tools",
  },
  {
    id: "writing",
    date: "c. 3300 BCE",
    shortDate: "3300 BCE",
    era: "Early cities",
    title: "Putting it in writing",
    text: "Around 3300 BCE, writing emerged alongside the growing cities of southern Mesopotamia. The earliest signs were pictures drawn on clay. Along with counting tokens and seals, writing helped people keep track of transactions. Even then, there were accounts to keep.",
    source: "The Metropolitan Museum of Art",
    url: "https://www.metmuseum.org/art/collection/search/325500",
  },
  {
    id: "printing",
    date: "868 CE",
    shortDate: "868",
    era: "Ink & paper",
    title: "A book you could unroll",
    text: "A surviving copy of the Diamond Sutra dates to 868 CE. Its Chinese text was printed from woodblocks onto a paper scroll nearly five metres long.",
    source: "British Library · International Dunhuang Programme",
    url: "https://idp.bl.uk/collection/51FDAEAFB4A24E2E9981692A98130BC8/",
  },
  {
    id: "telescope",
    date: "January 1610",
    shortDate: "1610",
    era: "Looking up",
    title: "A closer look at the sky",
    text: "In January 1610, Galileo observed moons orbiting Jupiter through a telescope he had built. That lens is still with us, preserved at Museo Galileo.",
    source: "Museo Galileo",
    url: "https://catalogue.museogalileo.it/room/RoomVIIBis.html",
  },
  {
    id: "flight",
    date: "17 December 1903",
    shortDate: "1903",
    era: "Taking flight",
    title: "Twelve seconds airborne",
    text: "On 17 December 1903, the Wright brothers made four powered flights near Kitty Hawk. Orville's first lasted 12 seconds. By the fourth flight, Wilbur stayed aloft for 59. All four flights happened that morning.",
    source: "National Park Service",
    url: "https://www.nps.gov/articles/firstflight.htm",
  },
  {
    id: "moon",
    date: "20 July 1969",
    shortDate: "1969",
    era: "Beyond Earth",
    title: "Landing on the Moon",
    text: "Apollo 11 landed on the Moon on 20 July 1969. Neil Armstrong and Buzz Aldrin explored the surface while Michael Collins piloted Columbia in lunar orbit. Four days later, all three were back on Earth.",
    source: "NASA",
    url: "https://www.nasa.gov/missions/apollo/apollo-11/apollo-11-mission-overview/",
  },
  {
    id: "web",
    date: "1989",
    shortDate: "1989",
    era: "Getting connected",
    title: "The World Wide Web",
    text: "Tim Berners-Lee invented the World Wide Web at CERN in 1989 to help scientists share information across universities and institutes. The first website explained the Web itself. Even the Web needed an introduction.",
    source: "CERN",
    url: "https://home.cern/science/computing/the-birth-of-the-web/",
  },
];
